version: 0.0
os: linux
files:
  - source: dthconnection.war
    destination: /usr/share/tomcat7/webapps/

hooks:
  ApplicationStop:
    - location: stop_application
      timeout: 300
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
  ApplicationStart:
    - location: write_codedeploy_config.sh
    - location: start_application
      timeout: 300
  ValidateService:
    - location: basic_health_check.sh
