version: 0.0
os: linux
files:
  - source: /dthconnection.war
    destination: /usr/share/tomcat8/webapps/
  - source: /scripts/configure_http_port.xsl
    destination: /usr/share/tomcat8/conf
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
